name: Deploy to VPS

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Project
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH and Deploy on VPS
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          host: $SSH_IP
          username: $SSH_USER
          key: $SSH_PRIVATE_KEY
          port: 22
          script: |
            git config --global url."https://$GITHUB_TOKEN:@github.com".insteadOf "https://github.com"
            cd ucob-guide/
            git pull
            yarn install
            yarn build
            rsync -a dist/ ${{ vars.SITE_DIR }}